#!/bin/bash

#1. Instalacion tomcat
# Actualizar el sistema
apt update -y
apt upgrade -y

# Instalar Java JDK
apt install openjdk-17-jdk
apt install openjdk-17-jre

# Crea un usuario y grupo tomcat si no existen
if id "tomcat" >/dev/null 2>&1; then
        echo "Usuario tomcat ya existe"
else
        useradd -m -d /opt/tomcat -U -s /bin/false tomcat
fi

# Descarga Apache Tomcat
wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.18/bin/apache-tomcat-10.1.18.tar.gz

# Crea un directorio de instalación
mkdir -p /opt/tomcat

# Descomprimime Apache Tomcat en el directorio de instalación
tar xzvf apache-tomcat-10.1.18.tar.gz -C /opt/tomcat --strip-components=1

# Cambiamos propietario y permisos del directorio de instalación
chown -R tomcat:tomcat /opt/tomcat
chmod -R u+x /opt/tomcat/bin

#2. Configuramos los usuarios administradores

# Añadir roles y usuarios a tomcat-users.xml
